apiVersion: v1
kind: Service
metadata:
  name: account-service-mysql
  labels:
    app: account-service
spec:
  ports:
    - port: 3306
  selector:
    app: account-service
    tier: mysql
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: account-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service-mysql
  labels:
    app: account-service
spec:
  selector:
    matchLabels:
      app: account-service
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: account-service
        tier: mysql
    spec:
      containers:
        - image: mysql:5.7.31
          name: mysql
          env:
            - name: MYSQL_DATABASE
              value: accounts
            - name: MYSQL_USER
              value: popo
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-pass
                  key: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
