spring:
    datasource:
        url: jdbc:mysql://${DATABASE_SERVER}:${DATABASE_PORT}/${DATABASE_NAME}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
        username: ${DATABASE_USER}
        password: ${DATABASE_PASSWORD}

        # Keep the connection alive if idle for a long time (needed in production)
        testWhileIdle: true
        validationQuery: SELECT 1
        initialize: true # Populate the database using 'data.sql'.
    jpa:
        hibernate.ddl-auto: update # create to recreate scheme
        show-sql: false
management:
  endpoints:
    web:
      exposure:
        include: [ "health", "prometheus" ]


logger:
  appender: ${LOGGER_ROOT_APPENDER:STDOUT}  #  logstash / STDOUT
  level: ${LOGGER_LEVEL:DEBUG}